apiVersion: v1
kind: Service
metadata:
  name: lab4
  labels:
    app: lab4
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: lab4
