apiVersion: v1
kind: Service
metadata:
  name: lab2
  labels:
    app: lab2
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3000
      nodePort: 31110
  selector:
    app: lab2
